import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};



export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body style={{ display: 'flex', minHeight: '100vh', margin: 0 }}>
        <nav style={{ width: '200px', background: '#eee', padding: '1rem' }}>
          <ul style={{ listStyle: 'none', padding: 0 }}>
            <li><a href="/home">Home</a></li>
            <li><a href="/invoices">Invoices</a></li>
            <li><a href="/customers">Customers</a></li>
          </ul>
        </nav>
        <main style={{ flex: 1, padding: '2rem' }}>
          {children}
        </main>
      </body>
    </html>
  );
}
